name: Publish library

on:
  release:
    types:
      - created

jobs:
  publish-library:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Retrieve AWS Secrets - Common Android
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          SECRET_NAME: common/gh-actions/android

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy Files From AWS S3
        run: |
          aws s3 cp s3://onelogin-endpoint/secrets/android/sonatype_credentials.gpg sonatype_credentials.gpg

      - name: Build Release
        run: ./gradlew oneloginoidc:assembleRelease

      - name: Source Jar and dokka
        run: ./gradlew androidSourcesJar javadocJar

        # Runs upload, and then closes & releases the repository
      - name: Publish to MavenCentral
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ env.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ env.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ env.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ env.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ env.SIGNING_SECRET_KEY_RING_FILE }}
          SONATYPE_STAGING_PROFILE_ID: ${{ env.SONATYPE_STAGING_PROFILE_ID }}
